# Generated by Django 3.0.5 on 2020-04-06 14:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[], max_length=100, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('str', models.CharField(max_length=1000, null=True)),
                ('list_str', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), null=True, size=None)),
                ('int', models.IntegerField(null=True)),
                ('list_int', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('float', models.FloatField(null=True)),
                ('list_float', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None)),
                ('bool', models.BooleanField(null=True)),
                ('list_bool', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), null=True, size=None)),
            ],
        ),
    ]
